export const business = {name:'Venus Journey',photographer:'Victoria',phone:'+34 644 656 260',email:'contactvenusjourney@gmail.com',instagram:'https://www.instagram.com/venus_journey/',youtube:'https://www.youtube.com/channel/UCYaefIs0paSU2noIdA9SjuQ'};
export const wa = (text='Hola Victoria, me gustaría consultar disponibilidad para una sesión de fotos.') => `https://wa.me/34644656260?text=${encodeURIComponent(text)}`;
export const services = [
 {slug:'fotografia-familiar',name:'Fotografía familiar',en:'Family photography',short:'Familias',image:'DSC05167_copy',alt:'Familia paseando de la mano por la playa',price:179,duration:'Hasta 2 horas',durationEn:'Up to 2 hours',count:'25 fotos retocadas como mínimo',countEn:'At least 25 edited photographs',intro:'Los abrazos de siempre. Un recuerdo para toda la vida.',description:'Una sesión de fotografía familiar e infantil en Cantabria, Bilbao y Bizkaia para guardar vuestra forma de estar juntos. Un paseo, un juego y esos pequeños gestos que hacen única a vuestra familia.',details:['Una sesión profesional de hasta 2 horas','Un mínimo de 25 fotografías retocadas','Un videoclip corto con los mejores momentos'],detailsEn:['A professional session of up to 2 hours','At least 25 edited photographs','A short highlight video'],body:'La playa, un paseo al aire libre o un lugar que tenga significado para vosotros: elegimos juntos el escenario. La idea es que los niños puedan ser ellos mismos y que también aparezcáis vosotros en los recuerdos.',faq:[['¿Podemos elegir el lugar?','Sí. Cuéntame dónde os gustaría hacer las fotos y valoramos juntos la luz, el entorno y el desplazamiento.'],['¿También haces fotografía infantil?','Sí. Las sesiones familiares pueden incluir retratos de los niños y momentos compartidos con sus padres. Cuéntame las edades al consultar.']]},
 {slug:'fotografia-embarazo',name:'La historia de tu embarazo',en:'Your pregnancy story',short:'Embarazo',image:'DSC05592_copy',alt:'Mujer embarazada con un vestido ligero en un paisaje natural',price:215,duration:'Hasta 2 horas',durationEn:'Up to 2 hours',count:'50 fotos retocadas como mínimo',countEn:'At least 50 edited photographs',intro:'La espera también forma parte de vuestra historia.',description:'Fotografía de embarazo en Cantabria y Bilbao, con una sesión natural en forma de paseo. Un espacio para recordar cómo se siente esta etapa, sin poses forzadas.',details:['Hasta 2 horas de sesión','Hasta 3 cambios de vestuario','Un mínimo de 50 fotografías retocadas','Un videoclip de aproximadamente 30 segundos'],detailsEn:['Up to 2 hours','Up to 3 outfit changes','At least 50 edited photographs','A video of approximately 30 seconds'],body:'Podemos dar un paseo y aprovechar la luz natural, o hablar de una sesión en casa. Antes de elegir la fecha, cuéntame cómo te encuentras, qué estilo te gusta y si quieres compartir el recuerdo con tu pareja o tus hijos.',faq:[['¿Cuándo debería consultar?','Puedes escribirme durante el embarazo para hablar de fechas y elegir un momento en el que te sientas cómoda.'],['¿Puedo cambiarme de ropa?','La sesión publicada incluye hasta tres cambios de vestuario. Podemos hablar antes de las prendas que te gustaría llevar.']]},
 {slug:'fotografia-recien-nacido',name:'Fotografía de recién nacido',en:'Newborn photography',short:'Recién nacido',image:'DSC08145_copy',alt:'Bebé descansando sobre una manta con las manos de sus padres',price:239,duration:'Hasta 3 horas',durationEn:'Up to 3 hours',count:'50 fotos retocadas como mínimo',countEn:'At least 50 edited photographs',intro:'Sus primeros días. Vuestro pequeño universo.',description:'Fotografía de recién nacido a domicilio en Cantabria, Bilbao y Bizkaia. Guardamos los primeros recuerdos de vuestro bebé en la comodidad de vuestro hogar o en un entorno exterior acordado.',details:['Hasta 3 horas de sesión','En vuestro hogar o al aire libre','Un mínimo de 50 fotografías retocadas','Un videoclip corto de la sesión'],detailsEn:['Up to 3 hours','At home or outdoors','At least 50 edited photographs','A short session highlight video'],body:'El hogar también es parte de la historia: sus rincones, vuestros brazos y esos primeros momentos juntos. Escríbeme para organizar la sesión y comentar los tiempos, el espacio y las necesidades de vuestra familia.',faq:[['¿Tenemos que ir a un estudio?','No. Esta sesión puede realizarse en la comodidad de vuestro hogar. También podemos valorar una localización exterior.'],['¿Cuánto dura la sesión?','El paquete publicado contempla hasta tres horas. Antes de reservar hablamos de cómo organizarla con vuestro bebé.']]},
 {slug:'video-familiar-bautizo',name:'Foto + vídeo familiar y bautizo',en:'Family & christening photo + film',short:'Foto + vídeo',image:'DSC01563_copy',alt:'Padres con su bebé vestido para su bautizo',price:299,duration:'Hasta 2 horas',durationEn:'Up to 2 hours',count:'50 fotos + película + copias',countEn:'50 photos + film + prints',intro:'Para volver a verlos. Y volver a sentirlo.',description:'Fotografía y vídeo familiar o de bautizo en Cantabria y Bilbao. Una colección de imágenes, una película y fotografías impresas para conservar los momentos que más os importan.',details:['Hasta 2 horas de sesión','Un mínimo de 50 fotografías retocadas','Película familiar de unos 3 minutos en alta resolución, con música','15 fotografías impresas a vuestra elección'],detailsEn:['Up to 2 hours','At least 50 edited photographs','An approximately 3-minute high-resolution family film with music','15 printed photographs of your choice'],body:'Una película conserva el movimiento, las miradas y la emoción del momento. Para un bautizo, cuéntame dónde y cuándo se celebra para concretar qué parte del día queréis recordar y organizar la cobertura.',faq:[['¿Qué incluye la película?','El paquete incluye un vídeo familiar de aproximadamente tres minutos, en alta resolución y con música.'],['¿Incluye fotografías impresas?','Sí. Incluye quince fotografías impresas a vuestra elección, además de las fotografías retocadas.']]}
];
export const stories=[
 {slug:'olgayadelina',name:'Olga y Adelina',location:'Weymouth, Reino Unido',locationEn:'Weymouth, United Kingdom',image:'P4730475',description:'Una relación especial entre madre e hija.',en:'A special bond between mother and daughter.',video:'TJSTzMz3gAs'},
 {slug:'javieraysergio',name:'Javiera y Sergio',location:'Madrid, España',locationEn:'Madrid, Spain',image:'P4040935',description:'Los primeros días con su primer bebé.',en:'The first days with their first baby.'},
 {slug:'garaziaitoramets',name:'Garazi, Aitor y Amets',location:'Laredo, España',locationEn:'Laredo, Spain',image:'P4870320-Edit-Edit',description:'Una historia familiar para volver a ella.',en:'A family story to return to.',video:'JZLdb6tMgLE'}
];
export const faqs=[
 ['¿Dónde haces las sesiones?','Trabajo en Cantabria, Bilbao y Bizkaia. Podemos hablar de una sesión en exteriores o en vuestro hogar, según el tipo de reportaje. Indícame tu localidad para confirmar disponibilidad y desplazamiento.'],
 ['¿Cómo puedo reservar?','Escríbeme por WhatsApp o correo con el tipo de sesión, vuestra localidad y las fechas que tenéis en mente. Te confirmaré disponibilidad y los detalles antes de que reserves.'],
 ['¿Qué diferencia hay entre el videoclip y la película familiar?','Las sesiones de familia, embarazo y recién nacido incluyen un videoclip corto. El paquete de foto + vídeo incluye una película de unos tres minutos y quince fotografías impresas.'],
 ['¿Cuánto cuesta una sesión?','Las sesiones publicadas son: familiar, 179 €; embarazo, 215 €; recién nacido, 239 €; y foto + vídeo familiar o bautizo, 299 €. Consulta las condiciones, el desplazamiento y el presupuesto final para tu sesión.'],
 ['¿Cuándo recibiremos las fotografías?','Te confirmaré el plazo de entrega y cómo recibiréis las imágenes al preparar vuestra reserva. Si las necesitas para una fecha especial, dímelo al consultar.']
];
